version: '3.7'
services:
  db:
    build: ./docker/postgres
    ports:
      - "5432:5432"
    env_file:
      - ./src/config/env/.env.development
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
