// Owner
// export enum PermissionOwner {
export enum PermissionApp {
  OWNER_ALL = 'OWNER:ALL',
  // }

  // // Auth
  // export enum PermissionAuth {
  AUTH_CREATE = 'AUTH:CREATE',
  AUTH_READ = 'AUTH:READ',
  AUTH_UPDATE = 'AUTH:UPDATE',
  AUTH_DELETE = 'AUTH:DELETE',
  AUTH_READ_UPDATE = 'AUTH:READ_UPDATE',
  AUTH_READ_UPDATE_DELETE = 'AUTH:READ_UPDATE_DELETE',
  AUTH_ALL = 'AUTH:ALL',
  // }

  // // Profile
  // export enum PermissionProfile {
  PROFILE_CREATE = 'PROFILE:CREATE',
  PROFILE_READ = 'PROFILE:READ',
  PROFILE_UPDATE = 'PROFILE:UPDATE',
  PROFILE_DELETE = 'PROFILE:DELETE',
  PROFILE_READ_UPDATE = 'PROFILE:READ_UPDATE',
  PROFILE_READ_UPDATE_DELETE = 'PROFILE:READ_UPDATE_DELETE',
  PROFILE_ALL = 'PROFILE:ALL',
  // }

  // // ProfileInfo
  // export enum PermissionProfileInfo {
  PROFILE_INFO_CREATE = 'PROFILE_INFO:CREATE',
  PROFILE_INFO_READ = 'PROFILE_INFO:READ',
  PROFILE_INFO_UPDATE = 'PROFILE_INFO:UPDATE',
  PROFILE_INFO_DELETE = 'PROFILE_INFO:DELETE',
  PROFILE_INFO_READ_UPDATE = 'PROFILE_INFO:READ_UPDATE',
  PROFILE_INFO_READ_UPDATE_DELETE = 'PROFILE_INFO:READ_UPDATE_DELETE',
  PROFILE_INFO_ALL = 'PROFILE_INFO:ALL',
  // }

  // // Session
  // export enum PermissionSession {
  SESSION_CREATE = 'SESSION:CREATE',
  SESSION_READ = 'SESSION:READ',
  SESSION_UPDATE = 'SESSION:UPDATE',
  SESSION_DELETE = 'SESSION:DELETE',
  SESSION_READ_UPDATE = 'SESSION:READ_UPDATE',
  SESSION_READ_UPDATE_DELETE = 'SESSION:READ_UPDATE_DELETE',
  SESSION_ALL = 'SESSION:ALL',
  // }

  // // Role
  // export enum PermissionRole {
  ROLE_CREATE = 'ROLE:CREATE',
  ROLE_READ = 'ROLE:READ',
  ROLE_UPDATE = 'ROLE:UPDATE',
  ROLE_DELETE = 'ROLE:DELETE',
  ROLE_READ_UPDATE = 'ROLE:READ_UPDATE',
  ROLE_READ_UPDATE_DELETE = 'ROLE:READ_UPDATE_DELETE',
  ROLE_ALL = 'ROLE:ALL',
  // }

  // // RolePermission
  // export enum PermissionRolePermission {
  ROLE_PERMISSION_CREATE = 'ROLE_PERMISSION:CREATE',
  ROLE_PERMISSION_READ = 'ROLE_PERMISSION:READ',
  ROLE_PERMISSION_UPDATE = 'ROLE_PERMISSION:UPDATE',
  ROLE_PERMISSION_DELETE = 'ROLE_PERMISSION:DELETE',
  ROLE_PERMISSION_READ_UPDATE = 'ROLE_PERMISSION:READ_UPDATE',
  ROLE_PERMISSION_READ_UPDATE_DELETE = 'ROLE_PERMISSION:READ_UPDATE_DELETE',
  ROLE_PERMISSION_ALL = 'ROLE_PERMISSION:ALL',
  // }

  // // File
  // export enum PermissionFile {
  FILE_CREATE = 'FILE:CREATE',
  FILE_READ = 'FILE:READ',
  FILE_UPDATE = 'FILE:UPDATE',
  FILE_DELETE = 'FILE:DELETE',
  FILE_READ_UPDATE = 'FILE:READ_UPDATE',
  FILE_READ_UPDATE_DELETE = 'FILE:READ_UPDATE_DELETE',
  FILE_ALL = 'FILE:ALL',
  // }

  // // FileMedia
  // export enum PermissionFileMedia {
  FILE_MEDIA_CREATE = 'FILE_MEDIA:CREATE',
  FILE_MEDIA_READ = 'FILE_MEDIA:READ',
  FILE_MEDIA_UPDATE = 'FILE_MEDIA:UPDATE',
  FILE_MEDIA_DELETE = 'FILE_MEDIA:DELETE',
  FILE_MEDIA_READ_UPDATE = 'FILE_MEDIA:READ_UPDATE',
  FILE_MEDIA_READ_UPDATE_DELETE = 'FILE_MEDIA:READ_UPDATE_DELETE',
  FILE_MEDIA_ALL = 'FILE_MEDIA:ALL',
  // }

  // // Attachment
  // export enum PermissionAttachment {
  ATTACHMENT_CREATE = 'ATTACHMENT:CREATE',
  ATTACHMENT_READ = 'ATTACHMENT:READ',
  ATTACHMENT_UPDATE = 'ATTACHMENT:UPDATE',
  ATTACHMENT_DELETE = 'ATTACHMENT:DELETE',
  ATTACHMENT_READ_UPDATE = 'ATTACHMENT:READ_UPDATE',
  ATTACHMENT_READ_UPDATE_DELETE = 'ATTACHMENT:READ_UPDATE_DELETE',
  ATTACHMENT_ALL = 'ATTACHMENT:ALL',
  // }

  // // Timetable
  // export enum PermissionTimetable {
  TIMETABLE_CREATE = 'TIMETABLE:CREATE',
  TIMETABLE_READ = 'TIMETABLE:READ',
  TIMETABLE_UPDATE = 'TIMETABLE:UPDATE',
  TIMETABLE_DELETE = 'TIMETABLE:DELETE',
  TIMETABLE_READ_UPDATE = 'TIMETABLE:READ_UPDATE',
  TIMETABLE_READ_UPDATE_DELETE = 'TIMETABLE:READ_UPDATE_DELETE',
  TIMETABLE_ALL = 'TIMETABLE:ALL',
  // }

  // // TimetableLecturer
  // export enum PermissionTimetableLecturer {
  TIMETABLE_LECTURER_CREATE = 'TIMETABLE_LECTURER:CREATE',
  TIMETABLE_LECTURER_READ = 'TIMETABLE_LECTURER:READ',
  TIMETABLE_LECTURER_UPDATE = 'TIMETABLE_LECTURER:UPDATE',
  TIMETABLE_LECTURER_DELETE = 'TIMETABLE_LECTURER:DELETE',
  TIMETABLE_LECTURER_READ_UPDATE = 'TIMETABLE_LECTURER:READ_UPDATE',
  TIMETABLE_LECTURER_READ_UPDATE_DELETE = 'TIMETABLE_LECTURER:READ_UPDATE_DELETE',
  TIMETABLE_LECTURER_ALL = 'TIMETABLE_LECTURER:ALL',
  // }

  // // TimetableSchedule
  // export enum PermissionTimetableSchedule {
  TIMETABLE_SCHEDULE_CREATE = 'TIMETABLE_SCHEDULE:CREATE',
  TIMETABLE_SCHEDULE_READ = 'TIMETABLE_SCHEDULE:READ',
  TIMETABLE_SCHEDULE_UPDATE = 'TIMETABLE_SCHEDULE:UPDATE',
  TIMETABLE_SCHEDULE_DELETE = 'TIMETABLE_SCHEDULE:DELETE',
  TIMETABLE_SCHEDULE_READ_UPDATE = 'TIMETABLE_SCHEDULE:READ_UPDATE',
  TIMETABLE_SCHEDULE_READ_UPDATE_DELETE = 'TIMETABLE_SCHEDULE:READ_UPDATE_DELETE',
  TIMETABLE_SCHEDULE_ALL = 'TIMETABLE_SCHEDULE:ALL',
  // }

  // // TimetableSubject
  // export enum PermissionTimetableSubject {
  TIMETABLE_SUBJECT_CREATE = 'TIMETABLE_SUBJECT:CREATE',
  TIMETABLE_SUBJECT_READ = 'TIMETABLE_SUBJECT:READ',
  TIMETABLE_SUBJECT_UPDATE = 'TIMETABLE_SUBJECT:UPDATE',
  TIMETABLE_SUBJECT_DELETE = 'TIMETABLE_SUBJECT:DELETE',
  TIMETABLE_SUBJECT_READ_UPDATE = 'TIMETABLE_SUBJECT:READ_UPDATE',
  TIMETABLE_SUBJECT_READ_UPDATE_DELETE = 'TIMETABLE_SUBJECT:READ_UPDATE_DELETE',
  TIMETABLE_SUBJECT_ALL = 'TIMETABLE_SUBJECT:ALL',
  // }

  // // Notification
  // export enum PermissionNotification {
  NOTIFICATION_CREATE = 'NOTIFICATION:CREATE',
  NOTIFICATION_READ = 'NOTIFICATION:READ',
  NOTIFICATION_UPDATE = 'NOTIFICATION:UPDATE',
  NOTIFICATION_DELETE = 'NOTIFICATION:DELETE',
  NOTIFICATION_READ_UPDATE = 'NOTIFICATION:READ_UPDATE',
  NOTIFICATION_READ_UPDATE_DELETE = 'NOTIFICATION:READ_UPDATE_DELETE',
  NOTIFICATION_ALL = 'NOTIFICATION:ALL',
  // }

  // // Message
  // export enum PermissionMessage {
  MESSAGE_CREATE = 'MESSAGE:CREATE',
  MESSAGE_READ = 'MESSAGE:READ',
  MESSAGE_UPDATE = 'MESSAGE:UPDATE',
  MESSAGE_DELETE = 'MESSAGE:DELETE',
  MESSAGE_READ_UPDATE = 'MESSAGE:READ_UPDATE',
  MESSAGE_READ_UPDATE_DELETE = 'MESSAGE:READ_UPDATE_DELETE',
  MESSAGE_ALL = 'MESSAGE:ALL',
  // }

  // // MessageConversation
  // export enum PermissionMessageConversation {
  MESSAGE_CONVERSATION_CREATE = 'MESSAGE_CONVERSATION:CREATE',
  MESSAGE_CONVERSATION_READ = 'MESSAGE_CONVERSATION:READ',
  MESSAGE_CONVERSATION_UPDATE = 'MESSAGE_CONVERSATION:UPDATE',
  MESSAGE_CONVERSATION_DELETE = 'MESSAGE_CONVERSATION:DELETE',
  MESSAGE_CONVERSATION_READ_UPDATE = 'MESSAGE_CONVERSATION:READ_UPDATE',
  MESSAGE_CONVERSATION_READ_UPDATE_DELETE = 'MESSAGE_CONVERSATION:READ_UPDATE_DELETE',
  MESSAGE_CONVERSATION_ALL = 'MESSAGE_CONVERSATION:ALL',
  // }

  // // MessageChat
  // export enum PermissionMessageChat {
  MESSAGE_CHAT_CREATE = 'MESSAGE_CHAT:CREATE',
  MESSAGE_CHAT_READ = 'MESSAGE_CHAT:READ',
  MESSAGE_CHAT_UPDATE = 'MESSAGE_CHAT:UPDATE',
  MESSAGE_CHAT_DELETE = 'MESSAGE_CHAT:DELETE',
  MESSAGE_CHAT_READ_UPDATE = 'MESSAGE_CHAT:READ_UPDATE',
  MESSAGE_CHAT_READ_UPDATE_DELETE = 'MESSAGE_CHAT:READ_UPDATE_DELETE',
  MESSAGE_CHAT_ALL = 'MESSAGE_CHAT:ALL',
  // }

  // // MessageChannel
  // export enum PermissionMessageChannel {
  MESSAGE_CHANNEL_CREATE = 'MESSAGE_CHANNEL:CREATE',
  MESSAGE_CHANNEL_READ = 'MESSAGE_CHANNEL:READ',
  MESSAGE_CHANNEL_UPDATE = 'MESSAGE_CHANNEL:UPDATE',
  MESSAGE_CHANNEL_DELETE = 'MESSAGE_CHANNEL:DELETE',
  MESSAGE_CHANNEL_READ_UPDATE = 'MESSAGE_CHANNEL:READ_UPDATE',
  MESSAGE_CHANNEL_READ_UPDATE_DELETE = 'MESSAGE_CHANNEL:READ_UPDATE_DELETE',
  MESSAGE_CHANNEL_ALL = 'MESSAGE_CHANNEL:ALL',
  // }

  // // MessageFeedback
  // export enum PermissionMessageFeedback {
  MESSAGE_FEEDBACK_CREATE = 'MESSAGE_FEEDBACK:CREATE',
  MESSAGE_FEEDBACK_READ = 'MESSAGE_FEEDBACK:READ',
  MESSAGE_FEEDBACK_UPDATE = 'MESSAGE_FEEDBACK:UPDATE',
  MESSAGE_FEEDBACK_DELETE = 'MESSAGE_FEEDBACK:DELETE',
  MESSAGE_FEEDBACK_READ_UPDATE = 'MESSAGE_FEEDBACK:READ_UPDATE',
  MESSAGE_FEEDBACK_READ_UPDATE_DELETE = 'MESSAGE_FEEDBACK:READ_UPDATE_DELETE',
  MESSAGE_FEEDBACK_ALL = 'MESSAGE_FEEDBACK:ALL',
  // }

  // // Event
  // export enum PermissionEvent {
  EVENT_CREATE = 'EVENT:CREATE',
  EVENT_READ = 'EVENT:READ',
  EVENT_UPDATE = 'EVENT:UPDATE',
  EVENT_DELETE = 'EVENT:DELETE',
  EVENT_READ_UPDATE = 'EVENT:READ_UPDATE',
  EVENT_READ_UPDATE_DELETE = 'EVENT:READ_UPDATE_DELETE',
  EVENT_ALL = 'EVENT:ALL',
  // }

  // // EventVote
  // export enum PermissionEventVote {
  EVENT_VOTE_CREATE = 'EVENT_VOTE:CREATE',
  EVENT_VOTE_READ = 'EVENT_VOTE:READ',
  EVENT_VOTE_UPDATE = 'EVENT_VOTE:UPDATE',
  EVENT_VOTE_DELETE = 'EVENT_VOTE:DELETE',
  EVENT_VOTE_READ_UPDATE = 'EVENT_VOTE:READ_UPDATE',
  EVENT_VOTE_READ_UPDATE_DELETE = 'EVENT_VOTE:READ_UPDATE_DELETE',
  EVENT_VOTE_ALL = 'EVENT_VOTE:ALL',
}

